# Generated by Django 5.1.6 on 2025-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="showsession",
            constraint=models.UniqueConstraint(
                fields=("planetarium_dome", "show_time"), name="unique_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("show_session", "row", "seat"), name="unique_ticket"
            ),
        ),
    ]
